### ISSUE TITLE
[victoria-metrics-k8s-stack] vmagent isn't deployed on helm release install

### ISSUE THREAD

**Issue by mdesouky** [VictoriaMetrics/helm-charts#1124] opened 2024-07-08 06:59 UTC
When deploying `victoria-metrics-k8s-stack` while setting `vmagent.enabled=true` it doesn't actually deploy `vmagent`, i have to apply a change to set `vmagent.enabled=false` and then back to `true` for it to be deployed properly

values file
```
nameOverride: ""
fullnameOverride: ""
tenant: "0"
# -- If this chart is used in "Argocd" with "releaseName" field then
# -- VMServiceScrapes couldn't select the proper services.
# -- For correct working need set value 'argocdReleaseOverride=$ARGOCD_APP_NAME'
argocdReleaseOverride: ""

# -- victoria-metrics-operator dependency chart configuration.
# -- For possible values refer to https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-operator#parameters
# -- also checkout here possible ENV variables to configure operator behaviour https://docs.victoriametrics.com/operator/vars.html
victoria-metrics-operator:
  enabled: true
  # -- Tells helm to clean up vm crd resources when uninstalling
  cleanupCRD: false
  cleanupImage:
    repository: bitnami/kubectl
    # use image tag that matches k8s API version by default
    # tag: 1.28.11
    pullPolicy: IfNotPresent

  createCRD: false # we disable crd creation by operator chart as we create them in this chart
  operator:
    # -- By default, operator converts prometheus-operator objects.
    disable_prometheus_converter: false
    # -- Enables custom config-reloader, bundled with operator.
    # It should reduce  vmagent and vmauth config sync-time and make it predictable.
    useCustomConfigReloader: true

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # -- If not set and create is true, a name is generated using the fullname template
  name: ""

## -- Create default rules for monitoring the cluster
defaultRules:
  create: true
  rules:
    etcd: false
    general: true
    k8s: true
    kubeApiserver: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: true
    kubeApiserverHistogram: true
    kubeApiserverSlos: true
    kubelet: true
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeScheduler: true
    kubeStateMetrics: true
    network: true
    node: true
    vmagent: true
    vmsingle: true
    vmcluster: true
    vmhealth: true
    alertmanager: true

  # -- Runbook url prefix for default rules
  runbookUrl: https://runbooks.prometheus-operator.dev/runbooks

  # Disabled VMRules
  disabled: {}

  ## Reduce app namespace alert scope
  appNamespacesTarget: ".*"

  # -- Labels for default rules
  labels: {}
  # -- Annotations for default rules
  annotations: {}

  # -- Additional labels for PrometheusRule alerts
  additionalRuleLabels: {}

  # -- Optional HTTP URL parameters added to each rule request
  params: {}

## -- Create default dashboards
defaultDashboardsEnabled: true

## -- Create experimental dashboards
experimentalDashboardsEnabled: true

## -- Create dashboards as CRDs (reuqires grafana-operator to be installed)
grafanaOperatorDashboardsFormat:
  enabled: false
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  allowCrossNamespaceImport: false

# Provide custom recording or alerting rules to be deployed into the cluster.
additionalVictoriaMetricsMap:
  #rule name
  workforce:
    groups:
    - name: KubernetesGeneral
      rules:
      - alert: KubernetesPodCrashLooping
        expr: increase(kube_pod_container_status_restarts_total[1m]) > 3
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Kubernetes pod crash looping (instance {{ $labels.instance }})
          description: "Pod {{ $labels.pod }} is crash looping\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: KubernetesContainerOomKiller
        expr: (kube_pod_container_status_restarts_total{} - kube_pod_container_status_restarts_total{namespace!="workforce"} offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[10m]) == 1
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Kubernetes container oom killer (instance {{ $labels.instance }})
          description: "Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} has been OOMKilled {{ $value }} times in the last 20 minutes."


    - name: WorkforceSLI
      interval: 5m
      rules:
      - record: sli:django_http_requests_latency_seconds_by_view_method_bucket:sum_by_view_method_le
        expr: sum(django_http_requests_latency_seconds_by_view_method_bucket{uptick_com_product_stream="WORKFORCE", uptick_com_environment="production"}) by (view, method, le)
      - record: sli:requests_total:sum_5m
        expr: sum(rate(django_http_requests_latency_including_middlewares_seconds_count{uptick_com_product_stream="WORKFORCE", uptick_com_environment="production"}[5m]))

    - name: WorkforceAlarms
      rules:
      - alert: SiteDown
        # Fire site down alarm if site is down for more than 1 minute
        # Only fire for sites that have an ingress older than 5 minutes (otherwise it will fire on migrations)
        expr:
          label_replace( (time() - kube_ingress_created > 500) > 60*5 , "app", "$1", "ingress", "(.*)-ingress") and on (app) probe_success{app_kubernetes_io_name="workforce"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          message: "Blackbox probe failed (instance {{ $labels.instance }} )"

      - alert: KubernetesContainerOomKiller
        # If it crashes more than twice in 20 minutes.
        expr: (kube_pod_container_status_restarts_total{} - kube_pod_container_status_restarts_total{namespace="workforce"} offset 20m >= 2) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[20m]) == 1
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Kubernetes container oom killer (instance {{ $labels.instance }})
          description: "Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} has been OOMKilled {{ $value }} times in the last 20 minutes."

  redis:
    groups:
    -
      name: Redis
      rules:
      -
        alert: RedisDown
        expr: |
          redis_up{service="redis-metrics-metrics"} == 0
        for: 2m
        labels:
          severity: error
        annotations:
          summary: "Redis&reg; instance {{ $labels.instance }} down"
          description: "Redis&reg; instance {{ $labels.instance }} is down"
      -
        alert: RedisMemoryHigh
        expr: >
          redis_memory_used_bytes{service="redis-metrics"} * 100
          /
          redis_memory_max_bytes{service="redis-metrics"}
          > 90
        for: 2m
        labels:
          severity: error
        annotations:
          summary: Redis&reg; instance "{{ $labels.instance }}" is using too much memory
          description: |
            Redis&reg; instance "{{ $labels.instance }}" is using "{{ $value }}"% of its available memory.
      -
        alert: RedisKeyEviction
        expr: |
          increase(redis_evicted_keys_total{service="redis-metrics"}[5m]) > 0
        for: 1s
        labels:
          severity: error
        annotations:
          summary: Redis&reg; instance "{{ $labels.instance }}" has evicted keys
          description: |
            Redis&reg; instance "{{ $labels.instance }}" has evicted "{{ $value }}" keys in the last 5 minutes.

externalVM:
  read:
    url: "${external_victoria_metrics_url}"
    basicAuth:
      username:
        name: victoria-metrics-auth
        key: username
      password:
        name: victoria-metrics-auth
        key: password
  write:
    url: "${external_victoria_metrics_remote_write_url}"
    basicAuth:
      username:
        name: victoria-metrics-auth
        key: username
      password:
        name: victoria-metrics-auth
        key: password

##############

# -- Configures vmsingle params
vmsingle:
  enabled: false

vmcluster:
  enabled: false

alertmanager:
  enabled: ${deploy_alert_manager}
  annotations: {}
  # spec for VMAlertmanager crd
  # https://docs.victoriametrics.com/operator/api.html#vmalertmanagerspec
  spec:
    selectAllByDefault: true
    image:
      tag: v0.25.0
    externalURL: ""
    routePrefix: /

    # if this one defined, it will be used for alertmanager configuration and config parameter will be ignored
    # configSecret: "alertmanager-config"

  config:
    templates:
      - "/etc/vm/configs/**/*.tmpl"
    global:
      resolve_timeout: 5m
    route:
      group_by: ['cluster', 'alertname', 'service', 'prometheus']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'null'
      routes:
      ###################################################
      # - matchers:
      #     - code_owner_channel!=""
      #     - severity=~"info|warning|critical"
      #   group_by: ["code_owner_channel", "alertgroup", "job"]
      #   receiver: slack-code-owners
      # ###################################################
      # ## Standard on-call routes
      # - matchers:
      #     - severity=~"info|warning|critical"
      #   receiver: slack-monitoring
      #   continue: true
      ###################################################
      # Silence target down alerts because we don't care about them
      - matchers:
          - alertname=~"TargetDown"
        receiver: 'null'
        continue: true
      # Ignore info alerts
      - matchers:
          - severity=~"info"
        receiver: 'null'
        continue: true
      # Slack notify warnings/criticals
      - matchers:
          - severity=~"warning|critical"
        receiver: 'slack'

    inhibit_rules:
      - target_matchers:
          - severity="warning"
        source_matchers:
          - severity="critical"
        # Apply inhibition if the alertname is the same.
        equal:
          - cluster
          - service
          - alertname
      # - target_matchers:
      #     - severity=info
      #   source_matchers:
      #     - severity=warning
      #   equal:
      #     - cluster
      #     - namespace
      #     - alertname
      # - target_matchers:
      #     - severity=info
      #   source_matchers:
      #     - alertname=InfoInhibitor
      #   equal:
      #     - cluster
      #     - namespace

    receivers:
      - name: 'null'
      - name: 'slack'
        slack_configs:
          - api_url: ${slack_alert_api_url}
            send_resolved: true
            title: |-
              [CLUSTER:{{ .CommonLabels.cluster | toUpper}}][{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.app }} {{ .CommonLabels.pod }}
              {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
                {{" "}}(
                {{- with .CommonLabels.Remove (stringSlice "prometheus" "cluster" "service" "container" "endpoint" "alertname" "job" "instance") }}
                  {{- range $index, $label := .SortedPairs -}}
                    {{ if $index }}, {{ end }}
                    {{- $label.Name }}="{{ $label.Value -}}"
                  {{- end }}
                {{- end -}}
                )
              {{- end }}
            text: >-
              {{ with index .Alerts 0 -}}
                :chart_with_upwards_trend: *<{{ .GeneratorURL }}|Graph>*
                {{- if .Annotations.runbook }}   :notebook: *<{{ .Annotations.runbook }}|Runbook>*{{ end }}
              {{ end }}

              *Alert details*:

              {{ range .Alerts -}}
                *Alert:* {{ .Labels.alertname }}
              *Description:* {{ .Annotations.description -}}{{ .Annotations.message -}}
                {{ range (.Labels.Remove (stringSlice "prometheus" "service" "endpoint" "alertname" "instance" "severity" )).SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                {{ end }}
              {{ end }}
      # - name: "slack-monitoring"
      #   slack_configs:
      #     - api_url: ${slack_alert_api_url}
      #       # channel: "#channel"
      #       send_resolved: true
      #       title: '{{ template "slack.monzo.title" . }}'
      #       icon_emoji: '{{ template "slack.monzo.icon_emoji" . }}'
      #       color: '{{ template "slack.monzo.color" . }}'
      #       text: '{{ template "slack.monzo.text" . }}'
      #       actions:
      #         - type: button
      #           text: "Runbook :green_book:"
      #           url: "{{ (index .Alerts 0).Annotations.runbook_url }}"
      #         - type: button
      #           text: "Query :mag:"
      #           url: "{{ (index .Alerts 0).GeneratorURL }}"
      #         - type: button
      #           text: "Dashboard :grafana:"
      #           url: "{{ (index .Alerts 0).Annotations.dashboard }}"
      #         - type: button
      #           text: "Silence :no_bell:"
      #           url: '{{ template "__alert_silence_link" . }}'
      #         - type: button
      #           text: '{{ template "slack.monzo.link_button_text" . }}'
      #           url: "{{ .CommonAnnotations.link_url }}"
      # - name: slack-code-owners
      #   slack_configs:
      #     - channel: "#{{ .CommonLabels.code_owner_channel }}"
      #       send_resolved: true
      #       title: '{{ template "slack.monzo.title" . }}'
      #       icon_emoji: '{{ template "slack.monzo.icon_emoji" . }}'
      #       color: '{{ template "slack.monzo.color" . }}'
      #       text: '{{ template "slack.monzo.text" . }}'
      #       actions:
      #         - type: button
      #           text: "Runbook :green_book:"
      #           url: "{{ (index .Alerts 0).Annotations.runbook }}"
      #         - type: button
      #           text: "Query :mag:"
      #           url: "{{ (index .Alerts 0).GeneratorURL }}"
      #         - type: button
      #           text: "Dashboard :grafana:"
      #           url: "{{ (index .Alerts 0).Annotations.dashboard }}"
      #         - type: button
      #           text: "Silence :no_bell:"
      #           url: '{{ template "__alert_silence_link" . }}'
      #         - type: button
      #           text: '{{ template "slack.monzo.link_button_text" . }}'
      #           url: "{{ .CommonAnnotations.link_url }}"
      #
  # better alert templates for slack
  # source https://gist.github.com/milesbxf/e2744fc90e9c41b47aa47925f8ff6512
  monzoTemplate:
    enabled: true

  # extra alert templates
  templateFiles:
    {}
    # template_1.tmpl: |-
    #   {{ define "hello" -}}
    #   hello, Victoria!
    #   {{- end }}
    # template_2.tmpl: ""

  ingress:
    enabled: true
    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    # ingressClassName: nginx
    # Values can be templated
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: "services"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      alb.ingress.kubernetes.io/success-codes: 200-302
      alb.ingress.kubernetes.io/auth-type: oidc
      alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
      alb.ingress.kubernetes.io/auth-idp-oidc: '${oidc_settings}'
    labels: {}
    path: /
    # pathType is only for k8s > 1.19
    pathType: Prefix

    hosts:
      - alertmanager.onuptick.com
    ## Extra paths to prepend to every host configuration. This is useful when working with annotation based services.
    extraPaths: []
    # - path: /*
    #   backend:
    #     serviceName: ssl-redirect
    #     servicePort: use-annotation
    ## Or for k8s > 1.19
    # - path: /*
    #   pathType: Prefix
    #   backend:
    #     service:
    #       name: ssl-redirect
    #       port:
    #         name: service
    tls: []
    #  - secretName: alertmanager-ingress-tls
    #    hosts:
    #      - alertmanager.domain.com

vmalert:
  annotations: {}
  enabled: ${deploy_vmalert}
  # Controls whether VMAlert should use VMAgent or VMInsert as a target for remotewrite
  remoteWriteVMAgent: true
  # spec for VMAlert crd
  # https://docs.victoriametrics.com/operator/api.html#vmalertspec
  spec:
    datasource:
      url: "${external_victoria_metrics_url}"
      basicAuth:
        username:
          name: victoria-metrics-auth
          key: username
      password:
        name: victoria-metrics-auth
        key: password
    # notifier:
    #   url: "http://localhost:9093"
    # remoteWrite:
    #   url: "http://localhost:8428"
    # remoteRead:
    #   url: "http://localhost:8428"
    selectAllByDefault: true
    image:
      tag: v1.101.0
    evaluationInterval: 15s

    # External labels to add to all generated recording rules and alerts
    externalLabels: {}

  # extra vmalert annotation templates
  templateFiles:
    {}
    # template_1.tmpl: |-
    #   {{ define "hello" -}}
    #   hello, Victoria!
    #   {{- end }}
    # template_2.tmpl: ""

  ingress:
    enabled: true
    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    # ingressClassName: nginx
    # Values can be templated
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: "services"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      alb.ingress.kubernetes.io/success-codes: 200-302
      alb.ingress.kubernetes.io/auth-type: oidc
      alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
      alb.ingress.kubernetes.io/auth-idp-oidc: '${oidc_settings}'
    labels: {}
    path: /
    # pathType is only for k8s > 1.19
    pathType: Prefix

    hosts:
      - vmalert.onuptick.com
    ## Extra paths to prepend to every host configuration. This is useful when working with annotation based services.
    extraPaths: []
    # - path: /*
    #   backend:
    #     serviceName: ssl-redirect
    #     servicePort: use-annotation
    ## Or for k8s > 1.19
    # - path: /*
    #   pathType: Prefix
    #   backend:
    #     service:
    #       name: ssl-redirect
    #       port:
    #         name: service
    tls: []
    #  - secretName: vmalert-ingress-tls
    #    hosts:
    #      - vmalert.domain.com

vmagent:
  enabled: true
  annotations: {}
  # https://docs.victoriametrics.com/operator/api.html#vmagentremotewritespec
  # defined spec will be added to the remoteWrite configuration of VMAgent
  additionalRemoteWrites:
    []
    #- url: http://some-remote-write/api/v1/write
  # spec for VMAgent crd
  # https://docs.victoriametrics.com/operator/api.html#vmagentspec
  spec:
    selectAllByDefault: true
    image:
      tag: v1.101.0
    scrapeInterval: 20s
    externalLabels:
      # For multi-cluster setups it is useful to use "cluster" label to identify the metrics source.
      # For example:
      cluster: ${cluster_name}
      region: ${region}
      environment: ${environment}
    extraArgs:
      promscrape.streamParse: "true"
      # Do not store original labels in vmagent's memory by default. This reduces the amount of memory used by vmagent
      # but makes vmagent debugging UI less informative. See: https://docs.victoriametrics.com/vmagent/#relabel-debug
      promscrape.dropOriginalLabels: "true"
    resources:
      requests:
        cpu: ${vm_resources.requests_cpu}
        memory:  ${vm_resources.requests_memory}
      limits:
        cpu: ${vm_resources.limits_cpu}
        memory: ${vm_resources.limits_memory}
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ebs-csi-encrypted-gp3
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: ${vm_storage}
    remoteWriteSettings:
      showURL: true
    remoteWrite:
      - url: "${external_victoria_metrics_remote_write_url}"
        basicAuth:
          username:
            name: victoria-metrics-auth
            key: username
          password:
            name: victoria-metrics-auth
            key: password
    # additionalScrapeConfigs:
    #   - job_name: 'workforce-ingresses'
    #     metrics_path: /probe
    #     params:
    #       module: [http_2xx]
    #     kubernetes_sd_configs:
    #       - role: ingress
    #         namespaces:
    #           names:
    #           - workforce
    #     relabel_configs:
    #       # build the target param (the scrape target)
    #       # use the https:// address and health check part
    #       - source_labels: [__meta_kubernetes_ingress_scheme,__address__,__meta_kubernetes_ingress_path,__meta_kubernetes_ingress_annotation_alb_ingress_kubernetes_io_healthcheck_path]
    #         regex: (.+);(.+);(.+);(.*)
    #         replacement: ${1}://${2}${4}
    #         target_label: __param_target
    #       # Change where prometheus scrapes to target the blackbox exporter service
    #       - target_label: __address__
    #         replacement: blackbox-prometheus-blackbox-exporter.monitor.svc:9115
    #       # Stick target onto instance
    #       - source_labels: [__param_target]
    #         target_label: instance
    #       # Grab all the ingress labels
    #       - action: labelmap
    #         regex: __meta_kubernetes_ingress_label_(.+)
  ingress:
    enabled: true
    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    # ingressClassName: nginx
    # Values can be templated
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: "services"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      alb.ingress.kubernetes.io/success-codes: 200-302
      alb.ingress.kubernetes.io/auth-type: oidc
      alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
      alb.ingress.kubernetes.io/auth-idp-oidc: '${oidc_settings}'
    labels: {}
    path: /
    # pathType is only for k8s > 1.19
    pathType: Prefix

    hosts:
      - vmagent.${domain}
    ## Extra paths to prepend to every host configuration. This is useful when working with annotation based services.
    extraPaths: []
    # - path: /*
    #   backend:
    #     serviceName: ssl-redirect
    #     servicePort: use-annotation
    ## Or for k8s > 1.19
    # - path: /*
    #   pathType: Prefix
    #   backend:
    #     service:
    #       name: ssl-redirect
    #       port:
    #         name: service
    tls: []
    #  - secretName: vmagent-ingress-tls
    #    hosts:
    #      - vmagent.domain.com

#################################################
###              dependencies               #####
#################################################
# Grafana dependency chart configuration. For possible values refer to https://github.com/grafana/helm-charts/tree/main/charts/grafana#configuration
grafana:
  enabled: false

# prometheus-node-exporter dependency chart configuration. For possible values refer to https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml
prometheus-node-exporter:
  enabled: true
  resources:
    limits:
      cpu: 300m
      memory: 200M
    requests:
      cpu: 200m
      memory: 20M
  ## all values for prometheus-node-exporter helm chart can be specified here
  podLabels:
    ## Add the 'node-exporter' label to be used by serviceMonitor to match standard common usage in rules and grafana dashboards
    ##
    jobLabel: node-exporter
  extraArgs:
    - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
    - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$

  vmServiceScrape:
    # whether we should create a service scrape resource for node-exporter
    enabled: true

    # spec for VMServiceScrape crd
    # https://docs.victoriametrics.com/operator/api.html#vmservicescrapespec
    spec:
      jobLabel: jobLabel
      endpoints:
        - port: metrics
          metricRelabelConfigs:
            - action: drop
              source_labels: [mountpoint]
              regex: "/var/lib/kubelet/pods.+"
# kube-state-metrics dependency chart configuration. For possible values refer to https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/values.yaml
kube-state-metrics:
  enabled: true
  ## all values for kube-state-metrics helm chart can be specified here

  # spec for VMServiceScrape crd
  # https://docs.victoriametrics.com/operator/api.html#vmservicescrapespec
  vmServiceScrape:
    spec: {}

  #TODO: selector override for kube-state-metrics deployed separatelly

#################################################
###              Service Monitors           #####
#################################################
## Component scraping the kubelets
kubelet:
  enabled: true

  # -- Enable scraping /metrics/cadvisor from kubelet's service
  cadvisor: true
  # -- Enable scraping /metrics/probes from kubelet's service
  probes: true
  # spec for VMNodeScrape crd
  # https://docs.victoriametrics.com/operator/api.html#vmnodescrapespec
  spec:
    scheme: "https"
    honorLabels: true
    interval: "30s"
    scrapeTimeout: "5s"
    tlsConfig:
      insecureSkipVerify: true
      caFile: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    # drop high cardinality label and useless metrics for cadvisor and kubelet
    metricRelabelConfigs:
      - action: labeldrop
        regex: (uid)
      - action: labeldrop
        regex: (id|name)
      - action: drop
        source_labels: [__name__]
        regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
    relabelConfigs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - sourceLabels: [__metrics_path__]
        targetLabel: metrics_path
      - targetLabel: "job"
        replacement: "kubelet"
    # ignore timestamps of cadvisor's metrics by default
    # more info here https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4697#issuecomment-1656540535
    honorTimestamps: false
# -- Component scraping the kube api server
kubeApiServer:
  enabled: true
  # spec for VMServiceScrape crd
  # https://docs.victoriametrics.com/operator/api.html#vmservicescrapespec
  spec:
    endpoints:
      - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        # bearerTokenSecret:
        #   key: ""
        port: https
        scheme: https
        tlsConfig:
          caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          serverName: kubernetes
    jobLabel: component
    namespaceSelector:
      matchNames:
        - default
    selector:
      matchLabels:
        component: apiserver
        provider: kubernetes

# -- Component scraping the kube controller manager
kubeControllerManager:
  enabled: true

  ## If your kube controller manager is not deployed as a pod, specify IPs it can be found on
  ##
  endpoints: []
  # - 10.141.4.22
  # - 10.141.4.23
  # - 10.141.4.24

  ## If using kubeControllerManager.endpoints only the port and targetPort are used
  ##
  service:
    enabled: true
    port: 10257
    targetPort: 10257
    # selector:
    #   component: kube-controller-manager

  # spec for VMServiceScrape crd
  # https://docs.victoriametrics.com/operator/api.html#vmservicescrapespec
  spec:
    jobLabel: jobLabel
    endpoints:
      - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        # bearerTokenSecret:
        #   key: ""
        port: http-metrics
        scheme: https
        tlsConfig:
          caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          serverName: kubernetes

# -Component scraping kubeDns. Use either this or coreDns
kubeDns:
  enabled: false

# -- Component scraping coreDns. Use either this or kubeDns
coreDns:
  enabled: true
  service:
    enabled: true
    port: 9153
    targetPort: 9153
    selector:
      k8s-app: kube-dns

  # spec for VMServiceScrape crd
  # https://docs.victoriametrics.com/operator/api.html#vmservicescrapespec
  spec:
    jobLabel: jobLabel
    endpoints:
      - port: http-metrics
        bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token

## Component scraping etcd
##
kubeEtcd:
  enabled: false

## Component scraping kube scheduler
##
kubeScheduler:
  enabled: true

  ## If your kube scheduler is not deployed as a pod, specify IPs it can be found on
  ##
  endpoints: []
  # - 10.141.4.22
  # - 10.141.4.23
  # - 10.141.4.24

  ## If using kubeScheduler.endpoints only the port and targetPort are used
  ##
  service:
    enabled: true
    port: 10259
    targetPort: 10259
    # selector:
    #   component: kube-scheduler

  # spec for VMServiceScrape crd
  # https://docs.victoriametrics.com/operator/api.html#vmservicescrapespec
  spec:
    jobLabel: jobLabel
    endpoints:
      - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        # bearerTokenSecret:
        #   key: ""
        port: http-metrics
        scheme: https
        tlsConfig:
          caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt

## Component scraping kube proxy
##
kubeProxy:
  enabled: true

  ## If your kube proxy is not deployed as a pod, specify IPs it can be found on
  ##
  endpoints: []
  # - 10.141.4.22
  # - 10.141.4.23
  # - 10.141.4.24

  service:
    enabled: true
    port: 10249
    targetPort: 10249
    # selector:
    #   k8s-app: kube-proxy

  # spec for VMServiceScrape crd
  # https://docs.victoriametrics.com/operator/api.html#vmservicescrapespec
  spec:
    jobLabel: jobLabel
    endpoints:
      - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        # bearerTokenSecret:
        #   key: ""
        port: http-metrics
        scheme: http
        tlsConfig:
          caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt

## install vm operator crds
crds:
  enabled: true

## install prometheus operator crds
prometheus-operator-crds:
  enabled: false

```

**Comment by Haleygo** [comment] 2024-07-08 09:25
>vmagent.enabled=true it doesn't actually deploy vmagent, i have to apply a change to set vmagent.enabled=false and then back to true

Sound weird, both install and upgrade should have the same templated manifests. I also can't reproduce this issue with `helm install`.
Which version are you using here? Is this reproducible with latest version?

**Comment by mdesouky** [comment] 2024-07-08 23:50
@Haleygo latest version `0.23.5`

**Comment by Haleygo** [comment] 2024-07-10 15:40
0.23.5 works good on my test.
Just to confirm, is vmagent CR or vmagent pod not created in your installation?

**Comment by mdesouky** [comment] 2024-07-11 04:59
vmagent deployment and pods are not being created

**Comment by mdesouky** [comment] 2024-07-11 05:55
just tried another deployment and its the same result, the vmagent CR though has been left from a previous deployment since it doesn't really cleanup after itself

**Comment by mdesouky** [comment] 2024-07-11 06:10
Once I deployed the stack with `vmgent-enabled=false` then with `vmgent-enabled=true` everything got created and vmagent is up and running

**Comment by Haleygo** [comment] 2024-07-15 12:03
Could you try [v0.24.1](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.24.1) with fresh release?

**Comment by mdesouky** [comment] 2024-07-18 01:01
I just tried `v0.24.2` and nothing got installed except `prometheus-node-exporter` ,  `kube-state-metrics` and `victoria-metrics-operator`

**Comment by mdesouky** [comment] 2024-07-18 04:57
The CRs get created but never the deployments or the pods

**Comment by mdesouky** [comment] 2024-07-18 05:31
I think 0.24.1 actually made it alot worse, now nothing gets installed, not vmalert not alertmanager not vmagent, nothing works excepts the operator

**Comment by Haleygo** [comment] 2024-07-18 06:45
> The CRs get created but never the deployments or the pods

When CRs such as vmagent or vmalert are created, the vm-operator should manage them to create the corresponding workloads. 
Could you check vm-operator pod for related logs?

**Comment by mdesouky** [comment] 2024-07-26 01:50
These are the logs, this is one instance where on first deployment vmagent wasn't deployed, then I disabled it it, applied and then renabled it and applied and now it runs, no errors in the operator logs
[victoria-metrics-k8s-stack-victoria-metrics-operator-584cf6f644.log](https://github.com/user-attachments/files/16385590/victoria-metrics-k8s-stack-victoria-metrics-operator-584cf6f644.log)

**Comment by AndrewChubatiuk** [comment] 2024-09-04 05:12
hey @mdesouky 
can you reproduce this on the latest chart versions?

**Comment by AndrewChubatiuk** [comment] 2024-09-30 04:33
closing this issue as it might be related to operator performance, which was significantly improved in release 0.48.3
please create a new issue if it's still relevant

**Closed by AndrewChubatiuk** 2024-09-30 04:33 UTC
Labels: question

**Comment by trungtien** [comment] 2025-02-11 06:22
I changed vmagent.enabled to false and then back to true, but I had no luck—the vmagent still did not get created. I’m using the Victoria Metrics K8s Stack version 0.23.5

**Comment by trungtien** [comment] 2025-02-13 03:46
hi @AndrewChubatiuk , @Haleygo .


I installed the Victoria K8s Metrics Stack using Helm chart version 0.23.5 on two Kubernetes clusters.

The first Kubernetes cluster is functioning correctly, and the vmagent is successfully installed. When I run kubectl get deployments -n victoria-metrics-k8s-stack, I see the following deployments:

apache

Copy
NAME                                                   READY   UP-TO-DATE   AVAILABLE   AGE
victoria-metrics-k8s-stack-grafana                     1/1     1            1           35h
victoria-metrics-k8s-stack-kube-state-metrics          1/1     1            1           35h
victoria-metrics-k8s-stack-victoria-metrics-operator   1/1     1            1           35h
vmagent-victoria-metrics-k8s-stack                     3/3     3            3           20h
vmalert-victoria-metrics-k8s-stack                     1/1     1            1           20h
vminsert-victoria-metrics-k8s-stack                    2/2     2            2           20h
However, on the second Kubernetes cluster, the vmagent deployment is not visible when I run kubectl get deployments -n victoria-metrics-k8s-stack. The deployments in the second cluster are as follows:

apache

Copy
NAME                                                   READY   UP-TO-DATE   AVAILABLE   AGE
victoria-metrics-k8s-stack-grafana                     1/1     1            1           19h
victoria-metrics-k8s-stack-kube-state-metrics          1/1     1            1           19h
victoria-metrics-k8s-stack-victoria-metrics-operator   2/2     2            2           19h
vmalert-victoria-metrics-k8s-stack                     1/1     1            1           19h
vminsert-victoria-metrics-k8s-stack                    1/1     1            1           19h
I am unsure why the vmagent deployment is missing on the second Kubernetes cluster, as both clusters are running the same Kubernetes version, v1.25.10."
